version: 2.1
jobs:
  publish:
    docker:
      - image: orus/hugo-builder
    steps:
      - checkout
workflows:
  version: 2
  build_site_and_publish:
    jobs:
      - publish:
          filters:
            branches:
              only: master
